### ISSUE TITLE
Validation error with Json pydantic field

### ISSUE THREAD

**Issue by unidesigner** [awtkns/fastapi-crudrouter#131]
I use a JSONB column in Postgres, but I do get an error on the GET all route with my specified pydantic model with `json_field: Optional[pydantic.Json] = None` with proper json data in my database table. The exception is: 
```
..../python3.9/site-packages/fastapi/routing.py", line 137, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 2 validation errors for MyModel
response -> 0
  value is not a valid dict (type=type_error.dict)
```
Any idea how to fix that? Thanks.

**Comment by unidesigner** [comment]
This may be a related issue in [pydantic-sqlalchemy](https://github.com/tiangolo/pydantic-sqlalchemy/issues/19)

**Comment by awtkns** [comment]
Hi @unidesigner, my first thought is that this may be a pydantic-sqlalchemy issue as you mentioned. Would you be able to provide a more complete code example of how it is being used?

**Comment by unidesigner** [comment]
Hi @awtkns, thanks for getting back to me. Yes, you are right, it is likely a pydantic-sqlalchemy issue and I should go and check there. I will report back once I solve the issue.

**Comment by unidesigner** [comment]
I don't know if it was an issue with my code, but I could get the Json field to work with [SQLModel](https://github.com/tiangolo/sqlmodel/). I don't see that (async) SQLModel is yet supported but it would not be too difficult to add I guess, and I saw there is already a related issue #109 .
