### ISSUE TITLE
Are you considering adding authentication/authorization in the future?

### ISSUE THREAD

**Issue by serpulga** [awtkns/fastapi-crudrouter#164]

**Comment by ChuckMoe** [comment]
You can use other frameworks for it, like [fastapi-users](https://github.com/fastapi-users/fastapi-users), and then use the Depends functionality. Hope this helps.

**Comment by awtkns** [comment]
As @ChuckMoe correctly stated there are other frameworks that support this. Authentication / Authorization can also be handled through dependencies which has been supported from the initial release. 

More details can be found [here](https://fastapi-crudrouter.awtkns.com/dependencies).
