### ISSUE TITLE
Redis support?

### ISSUE THREAD

**Issue by gamesbook** [awtkns/fastapi-crudrouter#19]
It would be amazing to have support for directly storing/retrieving model data in Redis, without the need for an extra SQLAlchemy layer.

**Comment by awtkns** [comment]
It should be relatively easy to implement with just pydantic models + redis. Not sure on the timeline for this feature though.

**Comment by awtkns** [comment]
Also I am not entirely sure redis is meant to used in this way (as data store) as there is no guaranteed data persistence.

**Comment by gamesbook** [comment]
I think Redis **can** be used this way - and there are certainly use cases for small database-type apps that don't need the overhead of a Real Database (my use case is a generic messaging system that holds small amounts of data for users and only retains messages until they have been sent).  http://oldblog.antirez.com/post/redis-persistence-demystified.html provides some good insights and comparisons.

**Comment by awtkns** [comment]
Ok. That makes more sense. I'll see if I can implement this into a future version.

**Comment by gamesbook** [comment]
Hi - any reason you added a "wontfix" label? Is it possible to use a "planned_feature" label instead?
