### ISSUE TITLE
AttributeError: 'FieldInfo' object has no attribute 'name'

### ISSUE THREAD

**Issue by 0x587** [awtkns/fastapi-crudrouter#190]
I got this problem when I just try the demo!
*Python3.11.4*
```py
from pydantic import BaseModel
from fastapi import FastAPI
from fastapi_crudrouter import MemoryCRUDRouter as CRUDRouter


class Potato(BaseModel):
    id: int
    color: str
    mass: float
    pass


app = FastAPI()
app.include_router(CRUDRouter(schema=Potato))

import uvicorn

uvicorn.run(app)
```
![image](https://github.com/awtkns/fastapi-crudrouter/assets/40025941/d3e47999-98f3-449d-acc1-9e22109ae87a)
![image](https://github.com/awtkns/fastapi-crudrouter/assets/40025941/931fe009-5d34-45d6-b274-d524d61a8d95)

**Comment by SaladBreaker** [comment]
Hello, I encountered the same problem and by downgrading pydentic to `1.10.6` it got solved. I think this is only a temporary solution and somebody should definitely look into it.

**Comment by SaladBreaker** [comment]
Duplicate with: https://github.com/awtkns/fastapi-crudrouter/issues/189

**Comment by 0x587** [comment]
Thanks for your great advice.
I found that solving this problem only requires downgrading pydentic to a version below 2.0. Use the command 
``` bash
pip install "pydantic==1.*"
```
The problem occurs when pydantic2.x modifies
 ```py
BaseModel.__fields__
```
I provide a feasible solution here, just modify the ```schema_factory```function on line 22 of ```core/_utils.py```.
```py
# for handle pydantic 2.x migration
from pydantic import __version__ as pydantic_version

if int(pydantic_version.split('.')[0]) >= 2:
    # pydantic 2.x
    fields = {
        fk: (fv.annotation, ...)
        for fk,fv in schema_cls.model_fields.items()
        if fk != pk_field_name
    }
else:
    # pydantic 1.x
    fields = {
        f.name: (f.type_, ...)
        for f in schema_cls.__fields__.values()
        if f.name != pk_field_name
    }
``` 
I'll submit a Pull Request to fix this later.
