### ISSUE TITLE
route overload

### ISSUE THREAD

**Issue by DorskFR** [awtkns/fastapi-crudrouter#39]
Hi,

I am trying to overload a route.

My structure is that crudrouters are in a separate file:

crudrouter.py

```python
orders_router = SQLAlchemyCRUDRouter(
    schema=OrderSchema,
    create_schema=OrderCreate,
    update_schema=OrderEdit,
    db_model=Order,
    db=get_db,
    prefix="orders",
    dependencies=[Depends(token_auth)],
)
```

main.py

```python
from crudrouters import orders_router
app.include_router(orders_router)

```

it works perfectly.

However when I try to overload: 

```python
@orders_router.get("/")
async def overload_orders():
    return "Hello world 1"

@orders_router.get("/orders")
async def overload_orders():
    return "Hello world 2"
```

Following your example:

```python
app = FastAPI()
router = CRUDRouter(model=mymodel)

@router.get('/{item_id}')
def overloaded_get_all():
    return 'My overloaded route'
```

I am unable to overload using the router.

I tried:
- using orders_routers.get() in the crudrouter.py right after the definition of the SQLAlchemyCRUDRouter
- using orders_routers.get() before and after the app.include_router
- using with and without the prefix defined in SQLAlchemyCRUDRouter
- using app.get() after the app.include_router

and finally:
- using app.get before the app.include_router

which works:

```python
@app.get("/orders")
async def overload_orders():
    return "successful overload"

app.include_router(orders_router)
```

Is this the normal behavior or I am missing something to properly use the feature?
Thank you

**Comment by awtkns** [comment]
Hello again @DorskFR. Thanks for the detailed issue as always.

I tried it myself and I think you issue is the trailing slash. Try this and let me know if it works.

```
@orders_router.get("")
async def overload_orders():
    return "Hello world 1"
```

**Comment by DorskFR** [comment]
Hello,

Thank you for your answer.

That was indeed my mistake: trailing slash + I forgot the dependencies of the router would still apply which makes perfect sense.

So as you wrote above to overload the route while staying within the context of the router and using app.get to completely overwrite the route including the dependencies.

Thank you!
