### ISSUE TITLE
Pagination fails when limit is null

### ISSUE THREAD

**Issue by EthanHaid** [awtkns/fastapi-crudrouter#41]
![image](https://user-images.githubusercontent.com/46946968/111834124-5f559d00-88b0-11eb-9ef0-08adabce6692.png)

pls sir i need this for PeRf TeSTiNg

**Comment by awtkns** [comment]
https://github.com/awtkns/fastapi-crudrouter/blob/6a562a92363a889ce25bb1ffb7f2c95140793ccc/fastapi_crudrouter/core/_utils.py#L58

**Comment by awtkns** [comment]
Thanks for finding this @EthanHaid. The it should be fixed in the newest version 🙏
