### ISSUE TITLE
Support for ormar backend

### ISSUE THREAD

**Issue by collerek** [awtkns/fastapi-crudrouter#44]
Hi,

I'm creator of [`ormar`](https://github.com/collerek/ormar) which is an async "mini" ORM with `pydantic` validation, that can be used directly (as request and response models) with `fastapi`.

I want to make `ormar` a full-fledged member of the `fastapi` ecosystem, so I'm asking if you would like to add `ormar` support to `fastapi-crudrouter`? I can probably issue a PR with this functionality if you are interested. :)

**Comment by awtkns** [comment]
Hey @collerek. I just took a look through omar and I would be totally on board with this.  I think cross collaboration with the community is great.

Implementation wise, it would recommend taking a look at the [sqlalchemy crudrouter](https://github.com/awtkns/fastapi-crudrouter/blob/master/fastapi_crudrouter/core/sqlalchemy.py) to base your implementation off of. From there, you can add omar as an implementation [here](https://github.com/awtkns/fastapi-crudrouter/tree/master/tests/implementations) for it to automatically be added to the test suite and tested.

I don't have a lot of time at the moment, so if you could PR this that would be awesome! I would however be happy to help should and issues arise.

Cool project btw!
