### ISSUE TITLE
Route overload ignored

### ISSUE THREAD

**Issue by DorskFR** [awtkns/fastapi-crudrouter#51]
Hello,

Me again, just reporting this so I do not forget.

I found a workaround but I observe the following behavior and I am not sure if that is a bug or not.

Router declared as:

```python
orders_router = SQLAlchemyCRUDRouter(
    schema=OrderSchema,
    create_schema=OrderCreate,
    update_schema=OrderEdit,
    db_model=Order,
    db=get_db,
    prefix="orders",
    dependencies=[Depends(token_auth)],
)
```

Update route overloaded like this:

```python
@orders_router.put("/{order_id}")
async def update_order(
    order_id: str, update_data: OrderEdit, db=Depends(get_db), user=Depends(token_auth)
):
    print(f"Overloaded {order_id}")
```

And it is ignored, the default Update route from SQLAlchemyCRUDRouter is preferred.

However with a create route it works:

```python
@orders_router.post("")
async def create_order(
    data: OrderCreate, db=Depends(get_db), user=Depends(token_auth),
):
    print("Overloaded")
```

And if I do this:

```python

orders_router = SQLAlchemyCRUDRouter(
    schema=OrderSchema,
    create_schema=OrderCreate,
    update_schema=OrderEdit,
    db_model=Order,
    db=get_db,
    prefix="orders",
    dependencies=[Depends(token_auth)],
    update_route=False,
)
```

Then the default one is not enabled apparently and my overloaded Update route is correctly used.
This also happens with a delete one route: orders_routers.delete("/{order_id}").

**Comment by awtkns** [comment]
Hi @DorskFR. The documentation definitely need to be more detailed on this, but I believe your routes are failing because your path is `/{order_id}` instead of `/{item_id}`.  Overloading it as `/{order_id}` is actually creating a separate here. 

The code shown below should work.
```python
@orders_router.put("/{item_id}")
async def update_order(
    order_id: str, update_data: OrderEdit, db=Depends(get_db), user=Depends(token_auth)
):
    print(f"Overloaded {order_id}")
```

I'll be looking at ways of eliminating this confusion the the future (maybe by treating all text in the `{...}` the same). Let me know if this fixes the issue.

**Comment by DorskFR** [comment]
Hi @awtkns ,

Oh, my bad I did not realize that `item_id` had to be named just like this.

Thank you very much for your answer and sorry for the noise then.

**Comment by awtkns** [comment]
No worries, it needs to be documented better
