### ISSUE TITLE
SQLAlchemyCRUDRouter Create is causing error

### ISSUE THREAD

**Issue by niranjanthilak** [awtkns/fastapi-crudrouter#63]
When I use the SQLAlchemyCRUDRouter in my project, the  Pydantic schema is not  being imported into the model on the create item calls.

I've traced this into the crudrouter __init__() call:
```
def _create(self, *args: Any, **kwargs: Any) -> Callable[..., Model]:
        def route(
            model: self.create_schema,  # type: ignore
            db: Session = Depends(self.db_func),
        ) -> Model:
            try:
                db_model: Model = self.db_model(**model.dict())
                db.add(db_model)
                db.commit()
                db.refresh(db_model)
                return db_model
            except IntegrityError:
                db.rollback()
                raise HTTPException(422, "Key already exists")

        return route
```

On a normal test:
Pydantic Object:  ` sample_object = AdminUserCreate(name="string",email='string',password='string')`
This works:     `print("Object: ",sample_object.dict()))`
This does not work:  `print("Dict: ",**sample_object.dict())`

I'm new to pydantic, so if it is a versioning issue, please do suggest the correct version this library requires.

**Comment by niranjanthilak** [comment]
Just an update, this was due to the way I've set up my database model.

I was using an explicit constructor within the model definition  and it was expecting a named tuple instead of the dict.

**Comment by awtkns** [comment]
Thanks for creating an issue. Glad you got it figured out.
