### ISSUE TITLE
Add support python-gino

### ISSUE THREAD

**Issue by Turall** [awtkns/fastapi-crudrouter#70]
Thank you for the project. I would like to add python-gino support. We use https://github.com/Turall/FastApi-boilerplate our template for creating an API. For our project, we want to use your module. But you don't support gino for this module.

**Comment by awtkns** [comment]
Hey @Turall, for sure! Gino support has always been at the back of my mind. 

Supporting it should be fairly easy and would make a good feature release. Is this something you wanted to tackle? I could point you in the right direction in terms of implementation (should be fairly similar to any of the other current implementations).

**Comment by Turall** [comment]
Of course. I already implemented it and want to send PR.

**Comment by awtkns** [comment]
Awesome, looking forward to it!
