### ISSUE TITLE
return dependency value

### ISSUE THREAD

**Issue by KarlCMB** [awtkns/fastapi-crudrouter#82]
Hi,
is it possible to "inject" somehow the value from a dependency to the  create or update model?
I would like to add the updating user in my create schema.
Any ideas?
Thank you for the great work

**Comment by awtkns** [comment]
Hi @KarlCMB. Thanks for the feedback! 

It is possible to do it with a dependency, However, currently I think the easiest way is to provide a custom implementation of the router (see #80). I am actively looking at ways of making the library more injectable; hopefully coming in a future release.
